In [3]:
import tensorflow as tf

In [7]:
x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], [1, 7, 5, 5], 
                                                        [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
# 'one- hot' ENCODING
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight') # 들어오는 값(4), 나가는 값(3, one-hot encoding)
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

# 가설 softmax로 간단하게 가능
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

# cost 함수
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())


#with tf.Session() as sess:
#    sess.run(tf.global_variables_initializer())



for step in range(2001):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    if step % 200 == 0:
        print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))


0 3.33405
200 0.619188
400 0.50079
600 0.420037
800 0.348133
1000 0.275726
1200 0.231704
1400 0.210417
1600 0.192571
1800 0.177403
2000 0.164363


In [8]:
# 예측 (오류 확인하기)

a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
print(a, sess.run(tf.arg_max(a, 1)))

[[  8.94073118e-03   9.91050363e-01   8.84691781e-06]] [1]


In [9]:
all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], 
                                          [1, 3, 4, 3], 
                                          [1, 1, 0, 1]]})
print(all, sess.run(tf.arg_max(all, 1)))

[[  8.94073118e-03   9.91050363e-01   8.84691781e-06]
 [  8.27869415e-01   1.60751149e-01   1.13794487e-02]
 [  2.14015774e-08   3.92442598e-04   9.99607503e-01]] [1 0 2]
