In [3]:
import tensorflow as tf
import numpy as np

In [14]:
x1_data = [73.,93.,89.,96.,73.]
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75.,93.,90.,100.,70]
y_data = [152.,185.,180.,196.,142.]

#placeholder (http://ljs93kr.tistory.com/33 참고)
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 +b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-05)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range (2001):
    cost_val, hy_val, _= sess.run([cost, hypothesis, train], feed_dict={x1: x1_data, x2: x2_data,x3:x3_data,Y:y_data})
    if step % 10 == 0:
        print(step,"cost: ", cost_val, '\nPrediction: \n',hy_val)

0 cost:  9875.9 
Prediction: 
 [ 73.92512512  71.74935913  79.6170578   86.27376556  50.66798019]
10 cost:  59.1417 
Prediction: 
 [ 161.54193115  177.11412048  183.40570068  199.29995728  131.04626465]
20 cost:  58.7363 
Prediction: 
 [ 161.77757263  177.45314026  183.71075439  199.63505554  131.31626892]
30 cost:  58.4225 
Prediction: 
 [ 161.74893188  177.47433472  183.70271301  199.6292572   131.34385681]
40 cost:  58.1104 
Prediction: 
 [ 161.71955872  177.49450684  183.69378662  199.62242126  131.37062073]
50 cost:  57.8 
Prediction: 
 [ 161.69026184  177.51460266  183.68482971  199.61558533  131.39730835]
60 cost:  57.4911 
Prediction: 
 [ 161.66104126  177.53466797  183.67593384  199.60879517  131.4239502 ]
70 cost:  57.1842 
Prediction: 
 [ 161.63194275  177.55467224  183.66706848  199.60203552  131.45051575]
80 cost:  56.8788 
Prediction: 
 [ 161.60290527  177.574646    183.65821838  199.59529114  131.477005  ]
90 cost:  56.5749 
Prediction: 
 [ 161.57391357  177.59454346  18

780 cost:  39.1326 
Prediction: 
 [ 159.75398254  178.84461975  183.09484863  199.16308594  133.16444397]
790 cost:  38.9247 
Prediction: 
 [ 159.7300415   178.86108398  183.08757019  199.15745544  133.18632507]
800 cost:  38.7179 
Prediction: 
 [ 159.70617676  178.87747192  183.08030701  199.15187073  133.2081604 ]
810 cost:  38.5122 
Prediction: 
 [ 159.68235779  178.89382935  183.07304382  199.14625549  133.22990417]
820 cost:  38.3076 
Prediction: 
 [ 159.65863037  178.91017151  183.06582642  199.14070129  133.25161743]
830 cost:  38.1041 
Prediction: 
 [ 159.63491821  178.92640686  183.05860901  199.13510132  133.27325439]
840 cost:  37.9017 
Prediction: 
 [ 159.61132812  178.94265747  183.05140686  199.12956238  133.29484558]
850 cost:  37.7005 
Prediction: 
 [ 159.58776855  178.95883179  183.04423523  199.1240387   133.31637573]
860 cost:  37.5002 
Prediction: 
 [ 159.56427002  178.97496033  183.03707886  199.11851501  133.33786011]
870 cost:  37.3011 
Prediction: 
 [ 159.540847

1660 cost:  24.5361 
Prediction: 
 [ 157.87840271  180.13346863  182.52404785  198.71983337  134.88145447]
1670 cost:  24.407 
Prediction: 
 [ 157.85958862  180.1464386   182.51834106  198.71536255  134.89874268]
1680 cost:  24.2785 
Prediction: 
 [ 157.84080505  180.15933228  182.51260376  198.71087646  134.91596985]
1690 cost:  24.1507 
Prediction: 
 [ 157.82206726  180.17221069  182.50691223  198.7064209   134.93315125]
1700 cost:  24.0237 
Prediction: 
 [ 157.8033905   180.18504333  182.50123596  198.70196533  134.95028687]
1710 cost:  23.8973 
Prediction: 
 [ 157.78477478  180.19786072  182.49559021  198.69755554  134.96739197]
1720 cost:  23.7716 
Prediction: 
 [ 157.76618958  180.21063232  182.48994446  198.69309998  134.98442078]
1730 cost:  23.6466 
Prediction: 
 [ 157.74766541  180.2233429   182.48429871  198.68867493  135.00140381]
1740 cost:  23.5223 
Prediction: 
 [ 157.72918701  180.23603821  182.47866821  198.6842804   135.01835632]
1750 cost:  23.3986 
Prediction: 
 [ 1

In [12]:
# matrix를 활용한 multi-variable linear regression

x_data = [[73.,80.,75.],[93.,88.,93.],[89.,91.,90.],[96.,98.,100.,],[73.,66.,70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]

X = tf.placeholder(tf.float32, shape= [None,3])
Y = tf.placeholder(tf.float32, shape= [None,1])

W = tf.Variable(tf.random_normal([3,1]),name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X,W)+b


cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-05)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range (2001):
    cost_val, hy_val, _= sess.run([cost, hypothesis, train], feed_dict={X: x_data,Y:y_data})
    if step % 10 == 0:
        print(step,"cost: ", cost_val, '\nPrediction: \n',hy_val)

0 cost:  45691.4 
Prediction: 
 [[-39.14475632]
 [-42.86378098]
 [-44.58982086]
 [-46.70431137]
 [-33.08003235]]
10 cost:  1.86609 
Prediction: 
 [[ 149.94421387]
 [ 184.40657043]
 [ 179.34384155]
 [ 197.15322876]
 [ 140.27038574]]
20 cost:  1.44717 
Prediction: 
 [[ 150.51664734]
 [ 185.09408569]
 [ 180.02156067]
 [ 197.89065552]
 [ 140.79516602]]
30 cost:  1.44653 
Prediction: 
 [[ 150.5186615 ]
 [ 185.0960083 ]
 [ 180.02377319]
 [ 197.8924408 ]
 [ 140.79701233]]
40 cost:  1.44591 
Prediction: 
 [[ 150.51896667]
 [ 185.09588623]
 [ 180.02394104]
 [ 197.89204407]
 [ 140.79730225]]
50 cost:  1.44527 
Prediction: 
 [[ 150.51924133]
 [ 185.09573364]
 [ 180.02409363]
 [ 197.8915863 ]
 [ 140.79756165]]
60 cost:  1.44465 
Prediction: 
 [[ 150.51954651]
 [ 185.09558105]
 [ 180.02424622]
 [ 197.89117432]
 [ 140.79782104]]
70 cost:  1.44402 
Prediction: 
 [[ 150.51982117]
 [ 185.09544373]
 [ 180.0243988 ]
 [ 197.89073181]
 [ 140.7980957 ]]
80 cost:  1.44339 
Prediction: 
 [[ 150.52012634]
 [ 1

 [[ 150.53749084]
 [ 185.0867157 ]
 [ 180.03411865]
 [ 197.8644104 ]
 [ 140.81480408]]
700 cost:  1.40507 
Prediction: 
 [[ 150.5377655 ]
 [ 185.08657837]
 [ 180.03425598]
 [ 197.86399841]
 [ 140.81507874]]
710 cost:  1.40446 
Prediction: 
 [[ 150.53805542]
 [ 185.08644104]
 [ 180.03443909]
 [ 197.86358643]
 [ 140.81535339]]
720 cost:  1.40385 
Prediction: 
 [[ 150.53834534]
 [ 185.08631897]
 [ 180.03459167]
 [ 197.86317444]
 [ 140.81561279]]
730 cost:  1.40325 
Prediction: 
 [[ 150.53860474]
 [ 185.08615112]
 [ 180.034729  ]
 [ 197.86273193]
 [ 140.81587219]]
740 cost:  1.40264 
Prediction: 
 [[ 150.53887939]
 [ 185.08602905]
 [ 180.03488159]
 [ 197.86230469]
 [ 140.81614685]]
750 cost:  1.40203 
Prediction: 
 [[ 150.53916931]
 [ 185.08589172]
 [ 180.03503418]
 [ 197.8618927 ]
 [ 140.81642151]]
760 cost:  1.40143 
Prediction: 
 [[ 150.53944397]
 [ 185.08575439]
 [ 180.03518677]
 [ 197.86148071]
 [ 140.81668091]]
770 cost:  1.40082 
Prediction: 
 [[ 150.53971863]
 [ 185.08560181]
 [ 18

1440 cost:  1.36083 
Prediction: 
 [[ 150.55807495]
 [ 185.0766449 ]
 [ 180.04551697]
 [ 197.83302307]
 [ 140.83506775]]
1450 cost:  1.36024 
Prediction: 
 [[ 150.55831909]
 [ 185.07649231]
 [ 180.0456543 ]
 [ 197.83258057]
 [ 140.83532715]]
1460 cost:  1.35964 
Prediction: 
 [[ 150.55859375]
 [ 185.07635498]
 [ 180.04580688]
 [ 197.83215332]
 [ 140.83560181]]
1470 cost:  1.35906 
Prediction: 
 [[ 150.55886841]
 [ 185.07623291]
 [ 180.04595947]
 [ 197.83175659]
 [ 140.83587646]]
1480 cost:  1.35849 
Prediction: 
 [[ 150.55912781]
 [ 185.07609558]
 [ 180.0460968 ]
 [ 197.8313446 ]
 [ 140.83613586]]
1490 cost:  1.35789 
Prediction: 
 [[ 150.55940247]
 [ 185.07595825]
 [ 180.04624939]
 [ 197.83091736]
 [ 140.83639526]]
1500 cost:  1.35729 
Prediction: 
 [[ 150.55967712]
 [ 185.07583618]
 [ 180.04640198]
 [ 197.83049011]
 [ 140.83668518]]
1510 cost:  1.35671 
Prediction: 
 [[ 150.55995178]
 [ 185.07571411]
 [ 180.04655457]
 [ 197.83009338]
 [ 140.83695984]]
1520 cost:  1.35614 
Prediction: